//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
    }
}
